- hosts: homelab
  vars_files:
    - group_vars/secrets.yml
    - group_vars/versions.yml

  roles:
  - { role: system, tags: ["system"] }
  - { role: common, tags: ["common"] }
  - { role: dropbear, tags: ["dropbear"] }
  - { role: ssl, tags: ["ssl"] }
  - { role: traefik, tags: ["traefik"] }
  - { role: pi-hole, tags: ["pi-hole"] }
  - { role: portainer, tags: ["portainer"] }
# - { role: home-assistant, tags: ["home-assistant"] }
  - { role: nextcloud, tags: ["nextcloud"] }
  - { role: gitea, tags: ["gitea"]}
  - { role: cleanup, tags: ["cleanup"]}